list: $/zmark/forms/models/form/columns.yaml
modelClass: Zmark\Forms\Models\Form
title: Form
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'zmark/forms/form/update/:id'
